### ISSUE TITLE
Official build ?

### ISSUE THREAD

**Issue by dbeniamine** [DevelopedInside/android_device_wileyfox_marmite#12]
Hello,

I am really happy to have LineageOS on my swift 2, my old phone (Wileyfox Swift) was officially supported by LineageOS and this was pretty nice (OTA upgrades, signed builds, ...). I think making this port official would be a great improvement for all users.

From what I understand your work is already almost acceptable, I saw an [issue on the Lineage Gerrit](https://review.lineageos.org/c/LineageOS/lineage_wiki/+/163094) from 2017 saying that the request for official build was abandoned due to a tree not conforming. My question is what should be done to have an official build and how can I help ?

Best regards,

David

**Comment by nikith290** [comment]
Hi David,

Thanks for you feedback.
Right now our work is NOT acceptable, because situation is pretty simular to 2017: our LOS17/16/15.1 DT didnt match with [LineageOS Device Support Requipments](https://github.com/LineageOS/charter/blob/master/device-support-requirements.md).

**What should be done:** 
1. Fix RIL bugs, such as: "preferrenced network type menu" and Dual Sim Dual Standby with LTE not working. 
2. Fix "Reboot to..." option _(only on LOS16/17)_
3. Fix sepolicy _(only on LOS16/17)_
4. Switch SeLinux to Enforcing _(only on LOS16/17)_
5. Build fully working TWRP 
6. Cleanup and edit commit history 
7. Write wiki page with flashing manual
8. Chose a person to maintain it
9. Make it official.

Sincerely,
Developed Inside Team
